# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 16:46
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

def load_data(apps, schema_editor):
    call_command("loaddata", "default_pages_and_perspectives_data.json")


def delete_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0022_merge_20180122_0916')
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]