# Generated by Django 2.1.4 on 2019-01-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0002_auto_20190108_1108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='Attendance',
        ),
        migrations.AlterModelTable(
            name='datasubmission',
            table='DataSubmission',
        ),
        migrations.AlterModelTable(
            name='financialinstitution',
            table='FinancialInstitution',
        ),
        migrations.AlterModelTable(
            name='fine',
            table='Fine',
        ),
        migrations.AlterModelTable(
            name='loanissue',
            table='LoanIssue',
        ),
        migrations.AlterModelTable(
            name='loanrepayment',
            table='LoanRepayment',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='Meeting',
        ),
        migrations.AlterModelTable(
            name='member',
            table='Member',
        ),
        migrations.AlterModelTable(
            name='outstandingwelfare',
            table='OutstandingWelfare',
        ),
        migrations.AlterModelTable(
            name='saving',
            table='Saving',
        ),
        migrations.AlterModelTable(
            name='technicaltrainer',
            table='TechnicalTrainer',
        ),
        migrations.AlterModelTable(
            name='vsla',
            table='Vsla',
        ),
        migrations.AlterModelTable(
            name='vslabankinghistory',
            table='VslaBankingHistory',
        ),
        migrations.AlterModelTable(
            name='vslacycle',
            table='VslaCycle',
        ),
        migrations.AlterModelTable(
            name='vsladbactivation',
            table='VslaDbActivation',
        ),
        migrations.AlterModelTable(
            name='vslaregion',
            table='VslaRegion',
        ),
        migrations.AlterModelTable(
            name='welfare',
            table='Welfare',
        ),
    ]
