# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-04 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0004_auto_20190304_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vslaregion',
            old_name='Id',
            new_name='id',
        ),
    ]
