# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-26 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0006_auto_20190304_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='MeetingId',
            new_name='Meeting',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='MemberId',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='fine',
            old_name='IssuedInMeetingId',
            new_name='IssuedInMeeting',
        ),
        migrations.RenameField(
            model_name='fine',
            old_name='MemberId',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='fine',
            old_name='PaidInMeetingId',
            new_name='PaidInMeeting',
        ),
        migrations.RenameField(
            model_name='loanissue',
            old_name='MeetingId',
            new_name='Meeting',
        ),
        migrations.RenameField(
            model_name='loanissue',
            old_name='MemberId',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='MeetingId',
            new_name='Meeting',
        ),
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='MemberId',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='CycleId',
            new_name='Cycle',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='VslaId',
            new_name='Vsla',
        ),
        migrations.RenameField(
            model_name='outstandingwelfare',
            old_name='MeetingId',
            new_name='Meeting',
        ),
        migrations.RenameField(
            model_name='outstandingwelfare',
            old_name='MemberId',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='outstandingwelfare',
            old_name='PaidInMeetingId',
            new_name='PaidInMeeting',
        ),
        migrations.RenameField(
            model_name='saving',
            old_name='MeetingId',
            new_name='Meeting',
        ),
        migrations.RenameField(
            model_name='saving',
            old_name='MemberId',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='vsla',
            old_name='FinancialInstitutionId',
            new_name='FinancialInstitution',
        ),
        migrations.RenameField(
            model_name='vsla',
            old_name='RegionId',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='vslacycle',
            old_name='VslaId',
            new_name='Vsla',
        ),
        migrations.RenameField(
            model_name='vsladbactivation',
            old_name='VslaId',
            new_name='Vsla',
        ),
        migrations.RenameField(
            model_name='welfare',
            old_name='MeetingId',
            new_name='Meeting',
        ),
        migrations.RenameField(
            model_name='welfare',
            old_name='MemberId',
            new_name='Member',
        ),
    ]
