# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0007_auto_20190326_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='vslacycle',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
