# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-26 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0008_vslacycle_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vsla',
            old_name='CBT',
            new_name='TechnicalTrainer',
        ),
    ]
