# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-31 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0009_auto_20190326_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='Cycle',
            new_name='VslaCycle',
        ),
    ]
