# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0010_auto_20190331_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='VslaCycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vsla_cycle', to='ledgerlink.VslaCycle'),
        ),
    ]
