# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-31 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0011_auto_20190331_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='VslaCycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgerlink.VslaCycle'),
        ),
    ]
