# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-19 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0014_auto_20190416_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialinstitution',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'managed': True, 'permissions': [('post_bank_uganda', 'can access Post Bank Uganda data'), ('finca_uganda_limited', 'can access Finca Uganda Limited data'), ('barclays_bank_of_uganda', 'can access Barclays Bank of Uganda data'), ('rural_finance_initiative', 'can access Rural Finance Initiative data')]},
        ),
    ]
