# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0015_auto_20190919_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='LoanIssue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledgerlink.LoanIssue'),
        ),
    ]
