# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-12 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0016_auto_20191212_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstandingwelfare',
            name='PaidInMeeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outstanding_welfare_paid_in_meeting_id', to='ledgerlink.Meeting'),
        ),
    ]
