# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-05 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0017_auto_20191212_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='VslaCreditScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RequestedLoanAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('DaysInArrears', models.IntegerField(blank=True)),
                ('AmountInArrears', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('LoanRepaymentHistory', models.CharField(blank=True, max_length=200)),
                ('LoanRepaymentRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('NumberOfLoansDisbursed', models.IntegerField(blank=True)),
                ('NumberOfYearsOfOperation', models.IntegerField(blank=True)),
                ('AverageAttendanceRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('VolumeOfSavingsInPreviousCycle', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('LoanFundUtilization', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('AverageSavingRateInCurrentCycle', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('PercentageOfMembersWithActiveLoan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('LoanWriteOffInPreviousCycle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PortfolioAtRisk', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('FinalScore', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('Decision', models.CharField(blank=True, max_length=255)),
                ('AssessmentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Vsla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgerlink.Vsla')),
            ],
            options={
                'db_table': 'VslaCreditScore',
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'list'),
            },
        ),
    ]
