# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0019_vslacreditscore_dateprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vslacreditscore',
            name='PreviousLoanNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
