# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0021_vslacreditscore_volumeofsavingsincurrentcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vslacreditscore',
            name='FilePath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
