# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-05-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerlink', '0022_vslacreditscore_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vslacreditscore',
            name='AverageAttendanceRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
